version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: logma-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: logma
      POSTGRES_USER: logma
      POSTGRES_PASSWORD: logma
    volumes:
      - logma_pg:/var/lib/postgresql/data

volumes:
  logma_pg:
